name: Trigger Update in personal_deploy

on:
  push:
    branches:
      - deploy-react  # Triggers on push to 'deploy-react' branch
    paths:
      - "web_app/**"  # Only when changes occur in 'web_app' folder

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update in personal_deploy
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOA_UPDATE_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type": "update-repo-from-zeroapp"}' \
            https://api.github.com/repos/PhamCongHiep2003/personal_deploy/dispatches
